name: Test and Deploy Web App
on: push

jobs:
  test_web_app:
    runs_on: ubuntu-latest
    steps:
      - name: Nginx Docker Image and Container
        run: 
          docker image pull nginx
          docker container run -d -p 8080:80 nginx
          python3 -c "import requests; r = requests.get('http://localhost:8080'); print(r.status_code)"
          curl -s localhost:8080